### ISSUE TITLE
Issue with rollup for sveltejs/template project

### ISSUE THREAD

**Issue by b2k** [homer0/svelte-extend#4]
Following the following rollup.config.js on a fresh sveltejs/template clone, I get the following error when building: `TypeError: plugin.options.call is not a function`.

```js
import svelte from 'rollup-plugin-svelte';
import commonjs from '@rollup/plugin-commonjs';
import resolve from '@rollup/plugin-node-resolve';
import livereload from 'rollup-plugin-livereload';
import { terser } from 'rollup-plugin-terser';
import css from 'rollup-plugin-css-only';
const svelteExtend = require('svelte-extend/rollup');
 
const production = !process.env.ROLLUP_WATCH;

function serve() {
	let server;

	function toExit() {
		if (server) server.kill(0);
	}

	return {
		writeBundle() {
			if (server) return;
			server = require('child_process').spawn('npm', ['run', 'start', '--', '--dev'], {
				stdio: ['ignore', 'inherit', 'inherit'],
				shell: true
			});

			process.on('SIGTERM', toExit);
			process.on('exit', toExit);
		}
	};
}

export default {
	input: 'src/main.js',
	output: {
		sourcemap: true,
		format: 'iife',
		name: 'app',
		file: 'public/build/bundle.js'
	},
	plugins: [
		svelte({
			compilerOptions: {
				// enable run-time checks when not in production
				dev: !production
			}
		}),
		// The one for `svelte-extend`
		svelteExtend({
			include: [], // Files to include.
			exclude: [], // Files to exclude.
			allowedMaxDepth: 0, // No limit.
		}),
		  // we'll extract any component CSS out into
		// a separate file - better for performance
		css({ output: 'bundle.css' }),

		// If you have external dependencies installed from
		// npm, you'll most likely need these plugins. In
		// some cases you'll need additional configuration -
		// consult the documentation for details:
		// https://github.com/rollup/plugins/tree/master/packages/commonjs
		resolve({
			browser: true,
			dedupe: ['svelte']
		}),
		commonjs(),

		// In dev mode, call `npm run start` once
		// the bundle has been generated
		!production && serve(),

		// Watch the `public` directory and refresh the
		// browser on changes when not in production
		!production && livereload('public'),

		// If we're building for production (npm run build
		// instead of npm run dev), minify
		production && terser()
	],
	watch: {
		clearScreen: false
	}
};

```

**Comment by homer0** [comment]
@b2k Hey 👋!

I'm really sorry I didn't answer you before, just a couple of weeks ago I noticed that I had an issue with my notifications. Were you able to figure it out? Anyways, I'll try to reproduce it, just to make sure this is still working.

Regards

**Comment by lambdagg** [comment]
Hi. Got this issue too, can you help?

**Comment by homer0** [comment]
@lambdagg @b2k I'm so sorry! I totally forgot about this, and I've had so much work lately that I couldn't make enough time to update the repos. I'll try to take a look during this week.

Really sorry for the delay!

**Comment by lambdagg** [comment]
Hi.
I'll be waiting for that. thanks for the amazing work! No need to apologize, we all got things to do.

**Comment by homer0** [comment]
Hey guys,

Sorry you had to wait for so long for this fix... personal life got crazy busy this year, so I couldn't find enough time to setup a test repo and try this out.

Today I finally bootstrapped a Svelte+Rollup boilerplate and tested this:

- Apparently, there's a new check in Rollup when the plugin has an `options` property where it tries to call it as an async function :P, and the `options` prop of this plugin are just the dictionary of the ones sent to the constructor. I removed the `options` prop and added `getOptions` method to do the same.
- After fixing the other issue, I found that I never added `transform` to be bound to the plugin class, so that was causing another error. That was a quick fix.
- Finally, the docs were wrong or something else changed in Rollup (I know I tested this when I first built it) and now this plugin needs to be above the official one, otherwise it receives the `.js` generated from the `.svelte`, and this plugin only works with the `.svelte`.

As an extra, I added a `map: null` to the formatted code, so it won't bother you with a warning about source maps... but I believe that's wrong, because the map will either show you the pre-extend or will put the extended component + the base one. Either way, PRs are welcome if you see an issue in there, I know source maps are not really that easy to handle and in this case, where we have "inheritance", I'm sure it will be a little bit complicated, so I don't want to promise something I know I can't make enough time to build.

This got closed automatically by GitHub, but if you see that the issue persist, please reopen it :D.
